/** AUTO-GENERATED by `uv run python -m scripts.export_types` — do not edit */

export type ApiResponse<T> = {
  success: boolean;
  data: T | null;
  message?: string | null;
  error?: ErrorDetail | null;
};

export type ErrorCode = "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "CONFLICT" | "INVALID_CREDENTIALS" | "TOKEN_EXPIRED" | "INTERNAL";

export type UserRole = "admin" | "user";

export type PlanType = "free" | "professional" | "enterprise";

export type ProjectStatus = "active" | "archived";

export type ProjectMemberRole = "owner" | "editor" | "viewer";

export type AdInputType = "image" | "text" | "video" | "url";

export type AdStatus = "pending" | "analyzing" | "completed" | "failed";

export type SimulationType = "ad_reaction" | "survey";

export type SimulationStatus = "pending" | "running" | "completed" | "failed";

export type ChatRole = "user" | "assistant";

export type CampaignObjective = "awareness" | "conversion";

export type SimulationEventType = "progress" | "milestone" | "completed" | "error";

export interface ErrorDetail {
  code: ErrorCode;
  message: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface UserOut {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  organization_id: string;
}

export interface UserProfileOut {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  organization_id: string;
}

export interface UserSettingsOut {
  theme: string;
  notifications: Record<string, unknown>;
}

export interface UpdateUserSettingsRequest {
  theme?: string | null;
  notifications?: Record<string, unknown> | null;
}

export interface OrganizationOut {
  id: string;
  name: string;
  plan_type: PlanType;
  created_at: string;
}

export interface CreateProjectRequest {
  name: string;
  description?: string | null;
}

export interface UpdateProjectRequest {
  name?: string | null;
  description?: string | null;
  status?: ProjectStatus | null;
}

export interface ProjectOut {
  id: string;
  organization_id: string;
  created_by: string;
  name: string;
  description: string | null;
  status: ProjectStatus;
  created_at: string;
  updated_at: string;
  my_role?: ProjectMemberRole | null;
}

export interface CreateTextAdRequest {
  project_id: string;
  name: string;
  headline: string;
  body: string;
  cta: string;
}

export interface AdOut {
  id: string;
  project_id: string;
  created_by: string;
  name: string;
  input_type: AdInputType;
  text_content?: Record<string, unknown> | null;
  storage_url?: string | null;
  analysis_status: AdStatus;
  analysis_result?: Record<string, unknown> | null;
  analysis_confidence?: number | null;
  created_at: string;
  updated_at: string;
}

export interface SimulationCreatedOut {
  id: string;
  status: SimulationStatus;
}

export interface SimulationSummaryOut {
  id: string;
  project_id: string;
  ad_id: string;
  status: SimulationStatus;
  persona_count: number;
  objective: CampaignObjective;
  results_summary?: Record<string, unknown> | null;
  created_at: string;
}

export interface PersonaConfig {
  count?: number;
  age_range?: unknown[] | null;
  gender_ratio?: Record<string, unknown> | null;
  regions?: unknown[] | null;
  include_clusters?: unknown[] | null;
}

export interface PredictionKpi {
  attention_score: number;
  sentiment_score: number;
  click_intent_rate: number;
  conversion_intent_rate: number;
  comprehension_score: number;
  recall_score: number;
}

export interface Recommendation {
  top_drivers?: string[];
  top_objections?: string[];
  copy_suggestions?: string[];
  cta_suggestions?: string[];
  next_ab_test?: string | null;
}

export interface SimulationEvent {
  type: SimulationEventType;
  simulation_id: string;
  node?: string | null;
  percent?: number | null;
  message?: string | null;
  data?: Record<string, unknown> | null;
}

export interface CreateChatSessionRequest {
  project_id?: string | null;
  title?: string;
}

export interface ChatSessionOut {
  id: string;
  user_id: string;
  project_id: string | null;
  title: string;
  created_at: string;
  updated_at: string;
}

export interface ChatMessageOut {
  id: string;
  session_id: string;
  role: ChatRole;
  content: string;
  meta?: Record<string, unknown> | null;
  tokens_used?: number | null;
  created_at: string;
}

export interface SendChatMessageRequest {
  content: string;
  meta?: Record<string, unknown> | null;
}

export interface ReportOut {
  id: string;
  simulation_id: string;
  report_data: Record<string, unknown>;
  pdf_url: string | null;
  disclaimer: string;
  created_at: string;
}

export interface AdminUserOut {
  id: string;
  email: string;
  name: string;
  role: UserRole;
  organization_id: string;
  is_active: boolean;
  last_login_at: string | null;
  created_at: string;
}

export interface CreateAdminUserRequest {
  organization_id: string;
  email: string;
  password: string;
  name: string;
  role?: UserRole;
}

export interface PatchAdminUserRequest {
  name?: string | null;
  role?: UserRole | null;
  is_active?: boolean | null;
}

export interface AdminChatSessionOut {
  id: string;
  user_id: string;
  user_email: string;
  project_id: string | null;
  title: string;
  message_count: number;
  updated_at: string;
}

export interface AdminUsageOut {
  user_count: number;
  organization_count: number;
  simulation_count: number;
  completed_simulations: number;
  chat_session_count: number;
}

export interface BillingPlanOut {
  organization_id: string;
  organization_name: string;
  plan_type: PlanType;
  display_name: string;
  price_krw: number;
  features: string[];
  is_current?: boolean;
}

export interface TokenResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
  user: UserOut;
}

export interface CreateSimulationRequest {
  ad_id: string;
  simulation_type?: SimulationType;
  objective?: CampaignObjective;
  persona_count?: number;
  persona_config?: PersonaConfig | null;
}

export interface Prediction {
  overall_score: number;
  verdict: string;
  kpi: PredictionKpi;
  confidence: number;
}

export interface DashboardOut {
  project_count: number;
  simulation_count: number;
  completed_simulations: number;
  recent_reports: ReportOut[];
}

export interface SimulationDetailOut {
  id: string;
  project_id: string;
  ad_id: string;
  status: SimulationStatus;
  persona_count: number;
  objective: CampaignObjective;
  results_summary?: Record<string, unknown> | null;
  created_at: string;
  simulation_type: SimulationType;
  persona_config?: Record<string, unknown> | null;
  requested_count?: number | null;
  received_count?: number | null;
  sample_size?: number | null;
  prediction?: Prediction | null;
  recommendation?: Recommendation | null;
  report_id?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  error_message?: string | null;
}
